/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.forms;

import controller.Controller;
import domain.User;
import javax.swing.JDialog;

/**
 *
 * @author Milica i Nikola
 */
public class FMainAdmin extends javax.swing.JFrame {

    /**
     * Creates new form FMain
     */
    public FMainAdmin() {
        initComponents();
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblLoggedUser = new javax.swing.JLabel();
        jMenuBarEdit = new javax.swing.JMenuBar();
        jMenuAdd = new javax.swing.JMenu();
        jMenuMovie = new javax.swing.JMenu();
        jMenuItemMovieNew = new javax.swing.JMenuItem();
        jMenuItemMovieChange = new javax.swing.JMenuItem();
        jMenuItemMovieDelete = new javax.swing.JMenuItem();
        jMenuMovieTheater = new javax.swing.JMenu();
        jMenuItemNewMovieTheater = new javax.swing.JMenuItem();
        jMenuItemChangeMovieTheater = new javax.swing.JMenuItem();
        jMenuUser = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlblLoggedUser.setText("User:");

        jMenuAdd.setText("Edit");

        jMenuMovie.setText("Movie");

        jMenuItemMovieNew.setText("New...");
        jMenuItemMovieNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMovieNewActionPerformed(evt);
            }
        });
        jMenuMovie.add(jMenuItemMovieNew);

        jMenuItemMovieChange.setText("Change...");
        jMenuItemMovieChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMovieChangeActionPerformed(evt);
            }
        });
        jMenuMovie.add(jMenuItemMovieChange);

        jMenuItemMovieDelete.setText("Delete...");
        jMenuItemMovieDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMovieDeleteActionPerformed(evt);
            }
        });
        jMenuMovie.add(jMenuItemMovieDelete);

        jMenuAdd.add(jMenuMovie);

        jMenuMovieTheater.setText("MovieTheater");

        jMenuItemNewMovieTheater.setText("New...");
        jMenuItemNewMovieTheater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNewMovieTheaterActionPerformed(evt);
            }
        });
        jMenuMovieTheater.add(jMenuItemNewMovieTheater);

        jMenuItemChangeMovieTheater.setText("Change...");
        jMenuItemChangeMovieTheater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemChangeMovieTheaterActionPerformed(evt);
            }
        });
        jMenuMovieTheater.add(jMenuItemChangeMovieTheater);

        jMenuAdd.add(jMenuMovieTheater);

        jMenuUser.setText("User");

        jMenuItem5.setText("New...");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenuUser.add(jMenuItem5);

        jMenuAdd.add(jMenuUser);

        jMenuBarEdit.add(jMenuAdd);

        setJMenuBar(jMenuBarEdit);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(jlblLoggedUser, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(243, Short.MAX_VALUE)
                .addComponent(jlblLoggedUser)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemMovieNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMovieNewActionPerformed
        JDialog dialog = new FMovieNew(this, true, FormMode.FORM_ADD);
        dialog.setVisible(true);
    }//GEN-LAST:event_jMenuItemMovieNewActionPerformed

    private void jMenuItemNewMovieTheaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNewMovieTheaterActionPerformed
        JDialog dialog = new FMovieTheaterNew(this, true, FormMode.FORM_ADD);
        dialog.setVisible(true);
    }//GEN-LAST:event_jMenuItemNewMovieTheaterActionPerformed

    private void jMenuItemChangeMovieTheaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemChangeMovieTheaterActionPerformed
        JDialog d = new FMovieTheaterNew(this, true, FormMode.FORM_VIEW);
        d.setVisible(true);
    }//GEN-LAST:event_jMenuItemChangeMovieTheaterActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        JDialog d = new FUserNew(this, true);
        d.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItemMovieChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMovieChangeActionPerformed
        JDialog d = new FMovieNew(null, true, FormMode.FORM_VIEW);
        d.setVisible(true);
    }//GEN-LAST:event_jMenuItemMovieChangeActionPerformed

    private void jMenuItemMovieDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMovieDeleteActionPerformed
        JDialog d = new FMovieNew(null, true, FormMode.FORM_DELETE);
        d.setVisible(true);
    }//GEN-LAST:event_jMenuItemMovieDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FMainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FMainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FMainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FMainAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuAdd;
    private javax.swing.JMenuBar jMenuBarEdit;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItemChangeMovieTheater;
    private javax.swing.JMenuItem jMenuItemMovieChange;
    private javax.swing.JMenuItem jMenuItemMovieDelete;
    private javax.swing.JMenuItem jMenuItemMovieNew;
    private javax.swing.JMenuItem jMenuItemNewMovieTheater;
    private javax.swing.JMenu jMenuMovie;
    private javax.swing.JMenu jMenuMovieTheater;
    private javax.swing.JMenu jMenuUser;
    private javax.swing.JLabel jlblLoggedUser;
    // End of variables declaration//GEN-END:variables

    private void prepareView() {
        setLocationRelativeTo(null);
        User user = (User) Controller.getInstance().getMap().get("current_admin");
        jlblLoggedUser.setText("User: " + user.getFirstName() + " " + user.getLastName());
    }
}
