/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.forms;

import controller.Controller;
import domain.Employee;
import domain.MovieTheater;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Milica i Nikola
 */
public class FUserNew extends javax.swing.JDialog {

    FormMode currentFormMode;

    /**
     * Creates new form FUserNew
     */
    public FUserNew(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        currentFormMode = FormMode.FORM_ADD;
        prepareView(FormMode.FORM_ADD);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelEmloyee = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jcmbboxAllMovieTheaters = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jtxtFirstName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtLastName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtUsername = new javax.swing.JTextField();
        jtxtPassword = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jbtnSave = new javax.swing.JButton();
        jbtnCancel = new javax.swing.JButton();
        jbtnChange = new javax.swing.JButton();
        jbtnAddAnother = new javax.swing.JButton();
        jbtnUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Employee");

        jpanelEmloyee.setBorder(javax.swing.BorderFactory.createTitledBorder("Data about employee"));

        jLabel1.setText("Works at:");

        jLabel2.setText("First name:");

        jLabel3.setText("Last name:");

        jLabel4.setText("username:");

        jLabel5.setText("password:");

        javax.swing.GroupLayout jpanelEmloyeeLayout = new javax.swing.GroupLayout(jpanelEmloyee);
        jpanelEmloyee.setLayout(jpanelEmloyeeLayout);
        jpanelEmloyeeLayout.setHorizontalGroup(
            jpanelEmloyeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelEmloyeeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanelEmloyeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jpanelEmloyeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcmbboxAllMovieTheaters, 0, 235, Short.MAX_VALUE)
                    .addComponent(jtxtFirstName)
                    .addComponent(jtxtLastName)
                    .addComponent(jtxtUsername)
                    .addComponent(jtxtPassword))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jpanelEmloyeeLayout.setVerticalGroup(
            jpanelEmloyeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelEmloyeeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanelEmloyeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcmbboxAllMovieTheaters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanelEmloyeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanelEmloyeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanelEmloyeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanelEmloyeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbtnSave.setText("Save");
        jbtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSaveActionPerformed(evt);
            }
        });

        jbtnCancel.setText("Cancel");
        jbtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelActionPerformed(evt);
            }
        });

        jbtnChange.setText("Change");
        jbtnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnChangeActionPerformed(evt);
            }
        });

        jbtnAddAnother.setText("Add another");
        jbtnAddAnother.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddAnotherActionPerformed(evt);
            }
        });

        jbtnUpdate.setText("Update");
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpanelEmloyee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnAddAnother)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnChange)
                .addGap(18, 18, 18)
                .addComponent(jbtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanelEmloyee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnSave)
                    .addComponent(jbtnCancel)
                    .addComponent(jbtnChange)
                    .addComponent(jbtnAddAnother)
                    .addComponent(jbtnUpdate))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSaveActionPerformed
        String firstName = jtxtFirstName.getText();
        String lastName = jtxtLastName.getText();
        String username = jtxtUsername.getText();
        String pasword = jtxtPassword.getText();
        MovieTheater movieTheater = (MovieTheater) jcmbboxAllMovieTheaters.getSelectedItem();
        Employee employee = Controller.getInstance().saveEmployee(new Employee(movieTheater, null, firstName, lastName, username, pasword));
        if (employee != null) {
            Controller.getInstance().getMap().put("current_employee", employee);//ako zatreba
            currentFormMode = FormMode.FORM_VIEW;
            prepareView(FormMode.FORM_VIEW);
            fillEmployee(employee);
            JOptionPane.showMessageDialog(null, "Employee " + employee.getUsername() + " saved!");
        }
    }//GEN-LAST:event_jbtnSaveActionPerformed

    private void jbtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_jbtnCancelActionPerformed

    private void jbtnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnChangeActionPerformed
        prepareView(FormMode.FORM_UPDATE);


    }//GEN-LAST:event_jbtnChangeActionPerformed

    private void jbtnAddAnotherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddAnotherActionPerformed
        prepareView(FormMode.FORM_ADD);
        currentFormMode = FormMode.FORM_ADD;
    }//GEN-LAST:event_jbtnAddAnotherActionPerformed

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed
        String firstName;
        String lastName;
        String username;
        String pasword;
        if (!jtxtFirstName.getText().isEmpty() && !jtxtLastName.getText().isEmpty() && !jtxtPassword.getText().isEmpty() && !jtxtUsername.getText().isEmpty()) {
            firstName = jtxtFirstName.getText();
            lastName = jtxtLastName.getText();
            username = jtxtUsername.getText();
            pasword = jtxtPassword.getText();
            MovieTheater movieTheater = (MovieTheater) jcmbboxAllMovieTheaters.getSelectedItem();
            Employee employee = (Employee) Controller.getInstance().getMap().get("current_employee");
            employee.setFirstName(firstName);
            employee.setLastName(lastName);
            employee.setPassword(pasword);
            employee.setUsername(username);
            employee.setMovieTheater(movieTheater);
            employee = Controller.getInstance().updateEmployee(employee);

            Controller.getInstance().getMap().put("current_employee", employee);
            JOptionPane.showMessageDialog(null, "Employee " + employee.getUsername() + " updated!");
            currentFormMode = FormMode.FORM_VIEW;
            prepareView(FormMode.FORM_VIEW);
        }
    }//GEN-LAST:event_jbtnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FUserNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FUserNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FUserNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FUserNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FUserNew dialog = new FUserNew(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbtnAddAnother;
    private javax.swing.JButton jbtnCancel;
    private javax.swing.JButton jbtnChange;
    private javax.swing.JButton jbtnSave;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JComboBox<MovieTheater> jcmbboxAllMovieTheaters;
    private javax.swing.JPanel jpanelEmloyee;
    private javax.swing.JTextField jtxtFirstName;
    private javax.swing.JTextField jtxtLastName;
    private javax.swing.JTextField jtxtPassword;
    private javax.swing.JTextField jtxtUsername;
    // End of variables declaration//GEN-END:variables

    private void prepareView(FormMode formmode) {

        List<MovieTheater> allMovieTheaters = Controller.getInstance().getAllMovieTheaters();
        for (MovieTheater movieTheater : allMovieTheaters) {
            jcmbboxAllMovieTheaters.addItem(movieTheater);

            if (formmode.equals(FormMode.FORM_ADD)) {

                jtxtLastName.setEditable(true);
                jtxtPassword.setEditable(true);
                jtxtUsername.setEditable(true);
                jtxtFirstName.setEditable(true);
                jbtnSave.setVisible(true);
                jbtnChange.setVisible(false);
                jbtnAddAnother.setVisible(false);
                jbtnUpdate.setVisible(false);

            }

            if (formmode.equals(FormMode.FORM_VIEW)) {
                jtxtLastName.setEditable(false);
                jtxtPassword.setEditable(false);
                jtxtUsername.setEditable(false);
                jtxtFirstName.setEditable(false);
                jbtnSave.setVisible(false);
                jbtnChange.setVisible(true);
                jbtnAddAnother.setVisible(true);
                jbtnUpdate.setVisible(false);
            }

            if (formmode.equals(FormMode.FORM_UPDATE)) {
                jtxtLastName.setEditable(true);
                jtxtPassword.setEditable(true);
                jtxtUsername.setEditable(true);
                jtxtFirstName.setEditable(true);
                jbtnSave.setVisible(true);
                jbtnChange.setVisible(false);
                jbtnAddAnother.setVisible(false);
                jbtnSave.setVisible(false);
                jbtnUpdate.setVisible(true);
            }
        }

    }

    private void fillEmployee(Employee employee) {
        jcmbboxAllMovieTheaters.setSelectedItem(employee.getMovieTheater());
        jtxtFirstName.setText(employee.getFirstName());
        jtxtLastName.setText(employee.getLastName());
        jtxtPassword.setText(employee.getPassword());
        jtxtUsername.setText(employee.getUsername());
    }
}
